// PRODUCTS
export const GET_PRODUCTS = "GET_PRODUCTS";
export const GET_PRODUCT_ID = "GET_PRODUCT_ID";
export const GET_PRODUCT_NAME = "GET_PRODUCT_NAME";
export const GET_PRODUCTS_CATEGORIES = "GET_PRODUCTS_CATEGORIES";
export const CREATE_PRODUCT = "CREATE_PRODUCT";
export const UPDATE_PRODUCT = "UPDATE_PRODUCT";
export const DELETE_PRODUCT = "DELETE_PRODUCT";

// USERS
export const GET_USERS = "GET_USERS";
export const GET_USER_ID = "GET_USER_ID";
export const CREATE_USER = "CREATE_USER";
export const UPDATE_USER = "UPDATE_USER";
export const DELETE_USER = "DELETE_USER";
